# Generated by Django 5.2.8 on 2026-04-27 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.CharField(max_length=64, unique=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('access_level', models.CharField(blank=True, max_length=50, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParkingUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'parking_units',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('row', models.PositiveIntegerField()),
                ('col', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spots', to='parking.parkingunit')),
            ],
            options={
                'db_table': 'parking_spots',
                'ordering': ['unit_id', 'row', 'col'],
            },
        ),
        migrations.CreateModel(
            name='ParkingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.CharField(max_length=64)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('exited_at', models.DateTimeField(blank=True, null=True)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parking_sessions', to='parking.parkingspot')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parking_sessions', to='parking.parkingunit')),
            ],
            options={
                'db_table': 'parking_sessions',
                'ordering': ['-entered_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='parkingspot',
            constraint=models.UniqueConstraint(fields=('unit', 'code'), name='unique_spot_code_per_unit'),
        ),
        migrations.AddConstraint(
            model_name='parkingspot',
            constraint=models.UniqueConstraint(fields=('unit', 'row', 'col'), name='unique_spot_position_per_unit'),
        ),
        migrations.AddIndex(
            model_name='parkingsession',
            index=models.Index(fields=['telegram_user_id', 'exited_at'], name='parking_ses_telegra_44dfec_idx'),
        ),
        migrations.AddIndex(
            model_name='parkingsession',
            index=models.Index(fields=['spot', 'exited_at'], name='parking_ses_spot_id_0ecfc6_idx'),
        ),
        migrations.AddConstraint(
            model_name='parkingsession',
            constraint=models.UniqueConstraint(condition=models.Q(('exited_at__isnull', True)), fields=('telegram_user_id',), name='unique_active_session_per_user'),
        ),
        migrations.AddConstraint(
            model_name='parkingsession',
            constraint=models.UniqueConstraint(condition=models.Q(('exited_at__isnull', True)), fields=('spot',), name='unique_active_session_per_spot'),
        ),
    ]
