# Generated by Django 5.2.8 on 2026-04-29 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='مثلاً: present, remote, busy. بعد از استفاده تغییرش ندهید.', max_length=50, unique=True, verbose_name='کد وضعیت')),
                ('title', models.CharField(help_text='مثلاً: حضوری، دورکار، جلسه، مرخصی', max_length=100, verbose_name='عنوان وضعیت')),
                ('emoji', models.CharField(blank=True, help_text='مثلاً: 🟢 یا 🏠 یا 🔴', max_length=10, null=True, verbose_name='ایموجی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است؟')),
                ('sort_order', models.IntegerField(default=100, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'وضعیت کاری',
                'verbose_name_plural': 'وضعیت\u200cهای کاری',
                'db_table': 'work_statuses',
                'ordering': ['sort_order', 'id'],
                'managed': False,
            },
        ),
    ]
