# Generated by Django 5.2.8 on 2026-05-02 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_workstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodReservation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('telegram_user_id', models.TextField(blank=True, null=True, verbose_name='شناسه تلگرام کاربر')),
                ('day_of_week', models.TextField(blank=True, null=True, verbose_name='روز هفته')),
                ('food', models.TextField(blank=True, null=True, verbose_name='غذای انتخاب\u200cشده')),
                ('reserved_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ثبت رزرو')),
                ('week_start_date', models.DateField(blank=True, null=True, verbose_name='تاریخ شروع هفته')),
                ('food_slot', models.TextField(blank=True, help_text='f1 یعنی غذای اول، f2 یعنی غذای دوم', null=True, verbose_name='انتخاب غذا')),
                ('portion_type', models.TextField(choices=[('full', 'پرس کامل'), ('half', 'نیم پرس'), ('khorak', 'خوراک')], default='full', verbose_name='نوع پرس')),
                ('portion_label', models.TextField(default='پرس کامل', verbose_name='عنوان نوع پرس')),
                ('portion_qty', models.DecimalField(decimal_places=2, default=1, max_digits=4, verbose_name='ضریب پرس')),
            ],
            options={
                'verbose_name': 'رزرو غذا',
                'verbose_name_plural': 'رزروهای غذا',
                'db_table': 'reservations',
                'ordering': ['-reserved_at', 'id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WeekMenu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day_of_week', models.TextField(verbose_name='روز هفته')),
                ('food1', models.TextField(blank=True, null=True, verbose_name='غذای اول')),
                ('food2', models.TextField(blank=True, null=True, verbose_name='غذای دوم')),
                ('week_start_date', models.DateField(verbose_name='تاریخ شروع هفته')),
            ],
            options={
                'verbose_name': 'برنامه غذایی هفته',
                'verbose_name_plural': 'برنامه\u200cهای غذایی هفته',
                'db_table': 'week_menu',
                'ordering': ['week_start_date', 'id'],
                'managed': False,
            },
        ),
    ]
