# Generated by Django 5.2.8 on 2026-05-04 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_foodreservation_weekmenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodReservationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutoff_hour', models.PositiveSmallIntegerField(default=19, help_text='عدد بین ۰ تا ۲۳. مثال: ۱۹ یعنی ساعت ۷ عصر.', verbose_name='ساعت پایان امکان تغییر غذا')),
                ('cutoff_minute', models.PositiveSmallIntegerField(default=0, help_text='عدد بین ۰ تا ۵۹.', verbose_name='دقیقه پایان امکان تغییر غذا')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است؟')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'تنظیمات رزرو غذا',
                'verbose_name_plural': 'تنظیمات رزرو غذا',
                'db_table': 'food_reservation_settings',
            },
        ),
        migrations.AlterModelOptions(
            name='employeeuser',
            options={'managed': False, 'verbose_name': 'کاربر کارمند', 'verbose_name_plural': 'کاربران کارمند'},
        ),
        migrations.AlterModelOptions(
            name='parkingsession',
            options={'ordering': ['-entered_at'], 'verbose_name': 'ورود و خروج پارکینگ', 'verbose_name_plural': 'ورود و خروج پارکینگ'},
        ),
        migrations.AlterModelOptions(
            name='parkingspot',
            options={'ordering': ['unit_id', 'row', 'col'], 'verbose_name': 'جایگاه پارکینگ', 'verbose_name_plural': 'جایگاه\u200cهای پارکینگ'},
        ),
        migrations.AlterModelOptions(
            name='parkingunit',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'واحد پارکینگ', 'verbose_name_plural': 'واحدهای پارکینگ'},
        ),
        migrations.AlterModelOptions(
            name='workstatus',
            options={'managed': False, 'ordering': ['parent_id', 'sort_order', 'id'], 'verbose_name': 'وضعیت کاری', 'verbose_name_plural': 'وضعیت\u200cهای کاری'},
        ),
        migrations.AlterField(
            model_name='parkingsession',
            name='entered_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ورود'),
        ),
        migrations.AlterField(
            model_name='parkingsession',
            name='exited_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان خروج'),
        ),
        migrations.AlterField(
            model_name='parkingsession',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parking_sessions', to='parking.parkingspot', verbose_name='جایگاه پارکینگ'),
        ),
        migrations.AlterField(
            model_name='parkingsession',
            name='telegram_user_id',
            field=models.CharField(max_length=64, verbose_name='شناسه تلگرام'),
        ),
        migrations.AlterField(
            model_name='parkingsession',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parking_sessions', to='parking.parkingunit', verbose_name='واحد پارکینگ'),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='code',
            field=models.CharField(max_length=50, verbose_name='کد جایگاه'),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='col',
            field=models.PositiveIntegerField(verbose_name='ستون'),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال است؟'),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='row',
            field=models.PositiveIntegerField(verbose_name='ردیف'),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spots', to='parking.parkingunit', verbose_name='واحد پارکینگ'),
        ),
        migrations.AlterField(
            model_name='parkingunit',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال است؟'),
        ),
        migrations.AlterField(
            model_name='parkingunit',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش'),
        ),
        migrations.AlterField(
            model_name='parkingunit',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان واحد'),
        ),
    ]
