# Generated by Django 5.2.8 on 2026-05-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_foodreservationsettings_alter_employeeuser_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='مثلاً: team_a یا sales یا support. بعد از استفاده تغییر ندهید.', max_length=100, unique=True, verbose_name='کد تیم')),
                ('title', models.CharField(help_text='مثلاً: تیم فروش، تیم پشتیبانی، تیم فنی', max_length=150, verbose_name='عنوان تیم')),
                ('emoji', models.CharField(blank=True, max_length=10, null=True, verbose_name='ایموجی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است؟')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'تیم',
                'verbose_name_plural': 'تیم\u200cها',
                'db_table': 'department_teams',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
