# Generated by Django 5.2.8 on 2026-05-05 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_departmentteam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentteam',
            name='code',
        ),
        migrations.RemoveField(
            model_name='departmentteam',
            name='emoji',
        ),
    ]
