# Generated by Django 5.2.8 on 2026-05-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_remove_departmentteam_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentteam',
            name='code',
            field=models.CharField(blank=True, help_text='مثلاً: team_a یا sales یا support. بعد از استفاده تغییرش ندهید.', max_length=100, null=True, unique=True, verbose_name='کد تیم'),
        ),
        migrations.AddField(
            model_name='departmentteam',
            name='emoji',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ایموجی'),
        ),
    ]
