# Generated by Django 5.2.8 on 2026-05-05 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0007_departmentteam_code_departmentteam_emoji'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentteam',
            name='emoji',
        ),
    ]
